### ISSUE TITLE
The link to the guide 404's

### ISSUE THREAD

**Issue by charlesbaer** [GoogleCloudPlatform/solutions-multicluster-gke-migration#25]
Great solution! FYI...the "Migrating workloads to a multi-cluster GKE environment with Multi-Cluster Services and Multi-Cluster Ingress" link loads a 404. Attaching screenshot.

![Screen Shot 2021-08-13 at 9 30 56 AM](https://user-images.githubusercontent.com/30347307/129364761-7cecf984-73c0-45a4-98f9-60036d692213.png)

**Comment by ferrarimarco** [comment]
Thanks for pointing this out! Deploying a fix now :)

**Comment by ferrarimarco** [comment]
Fixed in https://github.com/GoogleCloudPlatform/solutions-multicluster-gke-migration/commit/42e0e5fb4225fd380cb5b2950ca6583d8f73aab8

Thanks!
